### PR TITLE
Joke Search and write in text

### PR DESCRIPTION
**Pull request by ChuYungHuang**
Here is Version 1 without set search time,
I will set it at Version 2.

Please review and give some advise ,thanks.

### CODE REVIEW

**Review by chengchiehhung — CHANGES_REQUESTED** [review]
I would recommend that you modularized the part of writing files. It looks a little bit repetitive to use with open() structures between 19-25 lines. Thank you!

**Comment by ChuYungHuang** [comment]
I commit a new version called Version 2,which modified about [with open()] and add search time.
Please review again. Thanks!

**Comment by chengchiehhung** [comment]
Please raise a request again after you modified your code so that I can approve it.

**Comment by ChuYungHuang** [comment]
OK , here you are.
Thanks!

**Review by chengchiehhung — APPROVED** [review]
ok

**Pull request merged**
